/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Yahtzee1 extends javax.swing.JFrame {

    /**
     * Creates new form Yahtzee1
     */
    public Yahtzee1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        dobbelVak1 = new javax.swing.JLabel();
        dobbelVak3 = new javax.swing.JLabel();
        dobbelVak4 = new javax.swing.JLabel();
        dobbelVak5 = new javax.swing.JLabel();
        dobbelKnopAlle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        enen2 = new javax.swing.JButton();
        zessen1 = new javax.swing.JButton();
        enen1 = new javax.swing.JButton();
        tweeen2 = new javax.swing.JButton();
        drieen1 = new javax.swing.JButton();
        drieen2 = new javax.swing.JButton();
        vieren1 = new javax.swing.JButton();
        vieren2 = new javax.swing.JButton();
        vijven1 = new javax.swing.JButton();
        vijven2 = new javax.swing.JButton();
        zessen2 = new javax.swing.JButton();
        dobbelVak2 = new javax.swing.JLabel();
        tweeen1 = new javax.swing.JButton();
        scoreEnen1 = new javax.swing.JLabel();
        scoreTweeen1 = new javax.swing.JLabel();
        scoreDrieen1 = new javax.swing.JLabel();
        scoreVieren1 = new javax.swing.JLabel();
        scoreZessen1 = new javax.swing.JLabel();
        scoreVijven1 = new javax.swing.JLabel();
        scoreEnen2 = new javax.swing.JLabel();
        scoreTweeen2 = new javax.swing.JLabel();
        scoreDrieen2 = new javax.swing.JLabel();
        scoreVieren2 = new javax.swing.JLabel();
        scoreVijven2 = new javax.swing.JLabel();
        scoreZessen2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totaalBegin1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bonus1 = new javax.swing.JLabel();
        totaalDeel11 = new javax.swing.JLabel();
        totaalBegin2 = new javax.swing.JLabel();
        bonus2 = new javax.swing.JLabel();
        totaalDeel12 = new javax.swing.JLabel();
        berekenKnop11 = new javax.swing.JButton();
        berekenKnop12 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        javax.swing.JLabel fds = new javax.swing.JLabel();
        asdf = new javax.swing.JLabel();
        dads = new javax.swing.JLabel();
        sadfsd = new javax.swing.JLabel();
        fdsa = new javax.swing.JLabel();
        vasas = new javax.swing.JLabel();
        zcxv = new javax.swing.JLabel();
        three1 = new javax.swing.JLabel();
        three2 = new javax.swing.JLabel();
        carre1 = new javax.swing.JLabel();
        carre2 = new javax.swing.JLabel();
        full2 = new javax.swing.JLabel();
        full1 = new javax.swing.JLabel();
        kleine2 = new javax.swing.JLabel();
        kleine1 = new javax.swing.JLabel();
        grote2 = new javax.swing.JLabel();
        grote1 = new javax.swing.JLabel();
        topscore2 = new javax.swing.JLabel();
        topscore1 = new javax.swing.JLabel();
        chance2 = new javax.swing.JLabel();
        chance1 = new javax.swing.JLabel();
        threeKnop1 = new javax.swing.JButton();
        carreKnop1 = new javax.swing.JButton();
        fullKnop1 = new javax.swing.JButton();
        kleineKnop1 = new javax.swing.JButton();
        groteKnop1 = new javax.swing.JButton();
        topscoreKnop1 = new javax.swing.JButton();
        chanceKnop1 = new javax.swing.JButton();
        chanceKnop2 = new javax.swing.JButton();
        topscoreKnop2 = new javax.swing.JButton();
        groteKnop2 = new javax.swing.JButton();
        kleineKnop2 = new javax.swing.JButton();
        carreKnop2 = new javax.swing.JButton();
        fullKnop2 = new javax.swing.JButton();
        threeKnop2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        berekenKnop21 = new javax.swing.JButton();
        berekenKnop22 = new javax.swing.JButton();
        totaalDeel21 = new javax.swing.JLabel();
        totaalDeel22 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        totaalScore1 = new javax.swing.JLabel();
        totaalScore2 = new javax.swing.JLabel();
        winnaar = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        berekenKnopEind = new javax.swing.JButton();
        dobbelsteen1 = new javax.swing.JCheckBox();
        dobbelsteen2 = new javax.swing.JCheckBox();
        dobbelsteen3 = new javax.swing.JCheckBox();
        dobbelsteen4 = new javax.swing.JCheckBox();
        dobbelsteen5 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        beurtTekst = new javax.swing.JLabel();
        aantalGooien = new javax.swing.JLabel();

        jLabel11.setText("Gegooid:");

        jLabel19.setText("jLabel19");

        jToggleButton1.setText("jToggleButton1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1002, 650));
        getContentPane().setLayout(null);

        dobbelVak1.setText("0 ");
        getContentPane().add(dobbelVak1);
        dobbelVak1.setBounds(179, 14, 20, 14);

        dobbelVak3.setText("0");
        getContentPane().add(dobbelVak3);
        dobbelVak3.setBounds(380, 14, 23, 14);

        dobbelVak4.setText("0");
        getContentPane().add(dobbelVak4);
        dobbelVak4.setBounds(380, 57, 23, 14);

        dobbelVak5.setText("0");
        getContentPane().add(dobbelVak5);
        dobbelVak5.setBounds(578, 14, 78, 14);

        dobbelKnopAlle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dobbelKnopAlle.setText("Gooi!");
        dobbelKnopAlle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobbelKnopAlleActionPerformed(evt);
            }
        });
        getContentPane().add(dobbelKnopAlle);
        dobbelKnopAlle.setBounds(407, 50, 63, 25);

        jLabel1.setText("Enen");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 170, 40, 14);

        jLabel2.setText("Tweeën");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 210, 50, 14);

        jLabel3.setText("Drieën");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 250, 40, 14);

        jLabel4.setText("Vieren");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 290, 40, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Deel 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 121, 50, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Speler 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(118, 125, 49, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Speler 2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(284, 125, 49, 17);

        enen2.setText("Kies");
        enen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enen2ActionPerformed(evt);
            }
        });
        getContentPane().add(enen2);
        enen2.setBounds(284, 167, 60, 23);

        zessen1.setText("Kies");
        zessen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zessen1ActionPerformed(evt);
            }
        });
        getContentPane().add(zessen1);
        zessen1.setBounds(118, 367, 60, 23);

        enen1.setText("Kies");
        enen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enen1ActionPerformed(evt);
            }
        });
        getContentPane().add(enen1);
        enen1.setBounds(118, 167, 60, 23);

        tweeen2.setText("Kies");
        tweeen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweeen2ActionPerformed(evt);
            }
        });
        getContentPane().add(tweeen2);
        tweeen2.setBounds(284, 207, 60, 23);

        drieen1.setText("Kies");
        drieen1.setToolTipText("");
        drieen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drieen1ActionPerformed(evt);
            }
        });
        getContentPane().add(drieen1);
        drieen1.setBounds(118, 247, 60, 23);

        drieen2.setText("Kies");
        drieen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drieen2ActionPerformed(evt);
            }
        });
        getContentPane().add(drieen2);
        drieen2.setBounds(284, 247, 60, 23);

        vieren1.setText("Kies");
        vieren1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieren1ActionPerformed(evt);
            }
        });
        getContentPane().add(vieren1);
        vieren1.setBounds(118, 287, 60, 23);

        vieren2.setText("Kies");
        vieren2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieren2ActionPerformed(evt);
            }
        });
        getContentPane().add(vieren2);
        vieren2.setBounds(284, 287, 60, 23);

        vijven1.setText("Kies");
        vijven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vijven1ActionPerformed(evt);
            }
        });
        getContentPane().add(vijven1);
        vijven1.setBounds(118, 327, 60, 23);

        vijven2.setText("Kies");
        vijven2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vijven2ActionPerformed(evt);
            }
        });
        getContentPane().add(vijven2);
        vijven2.setBounds(284, 327, 60, 23);

        zessen2.setText("Kies");
        zessen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zessen2ActionPerformed(evt);
            }
        });
        getContentPane().add(zessen2);
        zessen2.setBounds(284, 367, 60, 23);

        dobbelVak2.setText("0");
        getContentPane().add(dobbelVak2);
        dobbelVak2.setBounds(179, 57, 14, 14);

        tweeen1.setText("Kies");
        tweeen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweeen1ActionPerformed(evt);
            }
        });
        getContentPane().add(tweeen1);
        tweeen1.setBounds(118, 207, 60, 23);

        scoreEnen1.setText("0");
        getContentPane().add(scoreEnen1);
        scoreEnen1.setBounds(94, 170, 10, 14);

        scoreTweeen1.setText("0");
        getContentPane().add(scoreTweeen1);
        scoreTweeen1.setBounds(94, 210, 10, 14);

        scoreDrieen1.setText("0");
        getContentPane().add(scoreDrieen1);
        scoreDrieen1.setBounds(94, 250, 10, 14);

        scoreVieren1.setText("0");
        getContentPane().add(scoreVieren1);
        scoreVieren1.setBounds(94, 290, 10, 14);

        scoreZessen1.setText("0");
        getContentPane().add(scoreZessen1);
        scoreZessen1.setBounds(94, 370, 10, 14);

        scoreVijven1.setText("0");
        getContentPane().add(scoreVijven1);
        scoreVijven1.setBounds(94, 330, 10, 14);

        scoreEnen2.setText("0");
        getContentPane().add(scoreEnen2);
        scoreEnen2.setBounds(260, 170, 10, 14);

        scoreTweeen2.setText("0");
        getContentPane().add(scoreTweeen2);
        scoreTweeen2.setBounds(260, 210, 10, 14);

        scoreDrieen2.setText("0");
        getContentPane().add(scoreDrieen2);
        scoreDrieen2.setBounds(260, 250, 10, 14);

        scoreVieren2.setText("0");
        getContentPane().add(scoreVieren2);
        scoreVieren2.setBounds(260, 290, 10, 14);

        scoreVijven2.setText("0");
        getContentPane().add(scoreVijven2);
        scoreVijven2.setBounds(260, 330, 10, 14);

        scoreZessen2.setText("0");
        getContentPane().add(scoreZessen2);
        scoreZessen2.setBounds(260, 370, 10, 14);

        jLabel16.setText("Vijven");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 330, 40, 14);

        jLabel17.setText("Zessen");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 370, 60, 14);

        jLabel6.setText("Bonus");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 450, 40, 14);

        jLabel18.setText("Totaal deel 1");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 490, 80, 14);

        totaalBegin1.setText("0");
        getContentPane().add(totaalBegin1);
        totaalBegin1.setBounds(94, 410, 10, 14);

        jLabel5.setText("Totaal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 410, 50, 14);

        bonus1.setText("0");
        getContentPane().add(bonus1);
        bonus1.setBounds(94, 450, 10, 14);

        totaalDeel11.setText("0");
        getContentPane().add(totaalDeel11);
        totaalDeel11.setBounds(94, 490, 10, 14);

        totaalBegin2.setText("0");
        getContentPane().add(totaalBegin2);
        totaalBegin2.setBounds(260, 410, 10, 14);

        bonus2.setText("0");
        getContentPane().add(bonus2);
        bonus2.setBounds(260, 450, 10, 14);

        totaalDeel12.setText("0");
        getContentPane().add(totaalDeel12);
        totaalDeel12.setBounds(260, 490, 10, 14);

        berekenKnop11.setText("Bereken");
        berekenKnop11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berekenKnop11ActionPerformed(evt);
            }
        });
        getContentPane().add(berekenKnop11);
        berekenKnop11.setBounds(118, 487, 80, 23);

        berekenKnop12.setText("Bereken");
        berekenKnop12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berekenKnop12ActionPerformed(evt);
            }
        });
        getContentPane().add(berekenKnop12);
        berekenKnop12.setBounds(284, 487, 80, 23);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Deel 2");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(409, 121, 50, 22);

        fds.setText("Three of a kind");
        getContentPane().add(fds);
        fds.setBounds(409, 170, 100, 14);

        asdf.setText("Carré");
        getContentPane().add(asdf);
        asdf.setBounds(454, 210, 40, 14);

        dads.setText("Full house");
        getContentPane().add(dads);
        dads.setBounds(433, 250, 60, 14);

        sadfsd.setText("Kleine straat");
        getContentPane().add(sadfsd);
        sadfsd.setBounds(421, 290, 70, 14);

        fdsa.setText("Grote straat");
        getContentPane().add(fdsa);
        fdsa.setBounds(422, 330, 70, 14);

        vasas.setText("Topscore");
        getContentPane().add(vasas);
        vasas.setBounds(437, 370, 60, 14);

        zcxv.setText("Chance");
        getContentPane().add(zcxv);
        zcxv.setBounds(445, 410, 50, 14);

        three1.setText("0");
        getContentPane().add(three1);
        three1.setBounds(491, 170, 10, 14);

        three2.setText("0");
        getContentPane().add(three2);
        three2.setBounds(710, 170, 10, 14);

        carre1.setText("0");
        getContentPane().add(carre1);
        carre1.setBounds(491, 210, 10, 14);

        carre2.setText("0");
        getContentPane().add(carre2);
        carre2.setBounds(710, 210, 10, 14);

        full2.setText("0");
        getContentPane().add(full2);
        full2.setBounds(710, 250, 10, 14);

        full1.setText("0");
        getContentPane().add(full1);
        full1.setBounds(491, 250, 10, 14);

        kleine2.setText("0");
        getContentPane().add(kleine2);
        kleine2.setBounds(710, 290, 10, 14);

        kleine1.setText("0");
        getContentPane().add(kleine1);
        kleine1.setBounds(491, 290, 10, 14);

        grote2.setText("0");
        getContentPane().add(grote2);
        grote2.setBounds(710, 330, 10, 14);

        grote1.setText("0");
        getContentPane().add(grote1);
        grote1.setBounds(491, 330, 10, 14);

        topscore2.setText("0");
        getContentPane().add(topscore2);
        topscore2.setBounds(710, 370, 10, 14);

        topscore1.setText("0");
        getContentPane().add(topscore1);
        topscore1.setBounds(491, 370, 10, 14);

        chance2.setText("0");
        getContentPane().add(chance2);
        chance2.setBounds(710, 410, 10, 14);

        chance1.setText("0");
        getContentPane().add(chance1);
        chance1.setBounds(491, 410, 10, 14);

        threeKnop1.setText("Kies");
        threeKnop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeKnop1ActionPerformed(evt);
            }
        });
        getContentPane().add(threeKnop1);
        threeKnop1.setBounds(515, 167, 60, 23);

        carreKnop1.setText("Kies");
        carreKnop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreKnop1ActionPerformed(evt);
            }
        });
        getContentPane().add(carreKnop1);
        carreKnop1.setBounds(515, 207, 60, 23);

        fullKnop1.setText("Kies");
        fullKnop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullKnop1ActionPerformed(evt);
            }
        });
        getContentPane().add(fullKnop1);
        fullKnop1.setBounds(514, 247, 60, 23);

        kleineKnop1.setText("Kies");
        kleineKnop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kleineKnop1ActionPerformed(evt);
            }
        });
        getContentPane().add(kleineKnop1);
        kleineKnop1.setBounds(514, 287, 60, 23);

        groteKnop1.setText("Kies");
        groteKnop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groteKnop1ActionPerformed(evt);
            }
        });
        getContentPane().add(groteKnop1);
        groteKnop1.setBounds(514, 327, 60, 23);

        topscoreKnop1.setText("Kies");
        topscoreKnop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topscoreKnop1ActionPerformed(evt);
            }
        });
        getContentPane().add(topscoreKnop1);
        topscoreKnop1.setBounds(514, 367, 60, 23);

        chanceKnop1.setText("Kies");
        chanceKnop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chanceKnop1ActionPerformed(evt);
            }
        });
        getContentPane().add(chanceKnop1);
        chanceKnop1.setBounds(514, 407, 60, 23);

        chanceKnop2.setText("Kies");
        chanceKnop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chanceKnop2ActionPerformed(evt);
            }
        });
        getContentPane().add(chanceKnop2);
        chanceKnop2.setBounds(734, 407, 60, 23);

        topscoreKnop2.setText("Kies");
        topscoreKnop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topscoreKnop2ActionPerformed(evt);
            }
        });
        getContentPane().add(topscoreKnop2);
        topscoreKnop2.setBounds(734, 367, 60, 23);

        groteKnop2.setText("Kies");
        groteKnop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groteKnop2ActionPerformed(evt);
            }
        });
        getContentPane().add(groteKnop2);
        groteKnop2.setBounds(734, 327, 60, 23);

        kleineKnop2.setText("Kies");
        kleineKnop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kleineKnop2ActionPerformed(evt);
            }
        });
        getContentPane().add(kleineKnop2);
        kleineKnop2.setBounds(734, 287, 60, 23);

        carreKnop2.setText("Kies");
        carreKnop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreKnop2ActionPerformed(evt);
            }
        });
        getContentPane().add(carreKnop2);
        carreKnop2.setBounds(734, 207, 60, 23);

        fullKnop2.setText("Kies");
        fullKnop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullKnop2ActionPerformed(evt);
            }
        });
        getContentPane().add(fullKnop2);
        fullKnop2.setBounds(734, 247, 60, 23);

        threeKnop2.setText("Kies");
        threeKnop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeKnop2ActionPerformed(evt);
            }
        });
        getContentPane().add(threeKnop2);
        threeKnop2.setBounds(734, 167, 60, 23);
        threeKnop2.getAccessibleContext().setAccessibleName("60");

        jLabel21.setText("Totaal deel 2");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(419, 490, 80, 14);

        berekenKnop21.setText("Bereken");
        berekenKnop21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berekenKnop21ActionPerformed(evt);
            }
        });
        getContentPane().add(berekenKnop21);
        berekenKnop21.setBounds(514, 487, 80, 23);

        berekenKnop22.setText("Bereken");
        berekenKnop22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berekenKnop22ActionPerformed(evt);
            }
        });
        getContentPane().add(berekenKnop22);
        berekenKnop22.setBounds(734, 487, 80, 23);

        totaalDeel21.setText("0");
        getContentPane().add(totaalDeel21);
        totaalDeel21.setBounds(491, 490, 10, 14);

        totaalDeel22.setText("0");
        getContentPane().add(totaalDeel22);
        totaalDeel22.setBounds(710, 490, 10, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Totale score");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(10, 527, 74, 17);

        totaalScore1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totaalScore1.setText("0");
        getContentPane().add(totaalScore1);
        totaalScore1.setBounds(94, 527, 8, 17);

        totaalScore2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totaalScore2.setText("0");
        getContentPane().add(totaalScore2);
        totaalScore2.setBounds(258, 528, 8, 17);

        winnaar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        winnaar.setText("Winnaar:");
        getContentPane().add(winnaar);
        winnaar.setBounds(10, 591, 96, 29);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Speler 1");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(515, 125, 49, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Speler 2");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(734, 125, 49, 17);

        berekenKnopEind.setText("Bereken");
        berekenKnopEind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berekenKnopEindActionPerformed(evt);
            }
        });
        getContentPane().add(berekenKnopEind);
        berekenKnopEind.setBounds(284, 527, 80, 23);

        dobbelsteen1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobbelsteen1.setSelected(true);
        dobbelsteen1.setText("Dobbelsteen 1, Gegooid:");
        getContentPane().add(dobbelsteen1);
        dobbelsteen1.setBounds(10, 9, 163, 23);

        dobbelsteen2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobbelsteen2.setSelected(true);
        dobbelsteen2.setText("Dobbelsteen 2, Gegooid:");
        getContentPane().add(dobbelsteen2);
        dobbelsteen2.setBounds(10, 52, 163, 23);

        dobbelsteen3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobbelsteen3.setSelected(true);
        dobbelsteen3.setText("Dobbelsteen 3, Gegooid:");
        getContentPane().add(dobbelsteen3);
        dobbelsteen3.setBounds(211, 9, 163, 23);

        dobbelsteen4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobbelsteen4.setSelected(true);
        dobbelsteen4.setText("Dobbelsteen 4, Gegooid:");
        getContentPane().add(dobbelsteen4);
        dobbelsteen4.setBounds(211, 52, 163, 23);

        dobbelsteen5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobbelsteen5.setSelected(true);
        dobbelsteen5.setText("Dobbelsteen 5, Gegooid:");
        getContentPane().add(dobbelsteen5);
        dobbelsteen5.setBounds(409, 9, 163, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("aantal keren te gooien:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(537, 54, 140, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Beurt:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(639, 11, 38, 17);

        beurtTekst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        beurtTekst.setText("Speler 1");
        getContentPane().add(beurtTekst);
        beurtTekst.setBounds(695, 11, 49, 17);

        aantalGooien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aantalGooien.setText("3");
        getContentPane().add(aantalGooien);
        aantalGooien.setBounds(695, 54, 8, 17);

        setBounds(0, 0, 842, 701);
    }// </editor-fold>//GEN-END:initComponents
        int dobbel1, dobbel2, dobbel3, dobbel4, dobbel5, punten, puntentotaal, score1, score2, gooien = 3, beurt = 1; 
      
    private void gooienActie(){
        gooien = 3;
        aantalGooien.setText(String.valueOf(gooien));   
    }
    private void beurt1Actie(){
        beurt = 1;
        beurtTekst.setText("Speler 1");
    }
    private void beurt2Actie(){
        beurt = 2;
        beurtTekst.setText("Speler 2");        
    }

    
    private void dobbelKnopAlleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobbelKnopAlleActionPerformed
        // alle dobbelstenen werken 
        if (dobbelsteen1.isSelected() & gooien > 0){
            dobbel1 = (int) (6*Math.random()+ 1);              
            dobbelVak1.setText(String.valueOf(dobbel1));
        }
        if (dobbelsteen2.isSelected() & gooien > 0){
            dobbel2 = (int) (6*Math.random()+ 1);
            dobbelVak2.setText(String.valueOf(dobbel2));
        }
        if (dobbelsteen3.isSelected() & gooien > 0){
            dobbel3 = (int) (6*Math.random()+ 1);
            dobbelVak3.setText(String.valueOf(dobbel3));
        }
        if (dobbelsteen4.isSelected() & gooien > 0){
            dobbel4 = (int) (6*Math.random()+ 1);
            dobbelVak4.setText(String.valueOf(dobbel4));
        }
        if (dobbelsteen5.isSelected() & gooien > 0){
            dobbel5 = (int) (6*Math.random()+ 1);
            dobbelVak5.setText(String.valueOf(dobbel5));
        }
        if (gooien > 0){
        gooien = gooien - 1;
        }
        aantalGooien.setText(String.valueOf(gooien));
                
    }//GEN-LAST:event_dobbelKnopAlleActionPerformed
   
    private void enen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enen1ActionPerformed
        //de actie voor de enen van speler 1
        if (beurt == 1){
            punten = 0;
            if (dobbel1 == 1){
                punten = punten + 1;
            }
            if (dobbel2 == 1){
                punten = punten + 1;
            }
            if (dobbel3 == 1){
                punten = punten + 1;
            }
            if (dobbel4 == 1){
                punten = punten + 1;
            }
            if (dobbel5 == 1){
                punten = punten + 1;  
            }

            scoreEnen1.setText(String.valueOf(punten));
            enen1.hide();
            beurt2Actie();
            gooienActie();
            
        }
    }//GEN-LAST:event_enen1ActionPerformed

    private void tweeen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweeen1ActionPerformed
        //de actie voor de tweeën van speler 1
        if (beurt == 1){
            punten = 0;
            if (dobbel1 == 2){
                punten = punten + 2;
            }
            if (dobbel2 == 2){
                punten = punten + 2;
            }
            if (dobbel3 == 2){
                punten = punten + 2;
            }
            if (dobbel4 == 2){
                punten = punten + 2;
            }
            if (dobbel5 == 2){
                punten = punten + 2;  
            }
            tweeen1.hide();
            scoreTweeen1.setText(String.valueOf(punten));
            beurt2Actie();
            gooienActie();
            
        }
    }//GEN-LAST:event_tweeen1ActionPerformed

    private void drieen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drieen2ActionPerformed
        // de actie voor drieën van speler 2
        if (beurt == 2){
            punten = 0;
            if (dobbel1 == 3){
                punten = punten + 3;
            }
            if (dobbel2 == 3){
                punten = punten + 3;
            }
            if (dobbel3 == 3){
                punten = punten + 3;
            }
            if (dobbel4 == 3){
                punten = punten + 3;
            }
            if (dobbel5 == 3){
                punten = punten + 3;  
            }
            drieen2.hide();
            scoreDrieen2.setText(String.valueOf(punten));
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_drieen2ActionPerformed

    private void drieen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drieen1ActionPerformed
        // de actie voor drieën van speler 1
        if (beurt == 1){
            punten = 0;
            if (dobbel1 == 3){
                punten = punten + 3;
            }
            if (dobbel2 == 3){
                punten = punten + 3;
            }
            if (dobbel3 == 3){
                punten = punten + 3;
            }
            if (dobbel4 == 3){
                punten = punten + 3;
            }
            if (dobbel5 == 3){
                punten = punten + 3;  
            }
            drieen1.hide();
            scoreDrieen1.setText(String.valueOf(punten));                
            gooienActie(); 
            beurt2Actie();
            
        }
    }//GEN-LAST:event_drieen1ActionPerformed

    private void vieren1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieren1ActionPerformed
        // de actie van vieren van speler 1
        if (beurt == 1){
            punten = 0;
            if (dobbel1 == 4){
                punten = punten + 4;
            }
            if (dobbel2 == 4){
                punten = punten + 4;
            }
            if (dobbel3 == 4){
                punten = punten + 4;
            }
            if (dobbel4 == 4){
                punten = punten + 4;
            }
            if (dobbel5 == 4){
                punten = punten + 4;  
            }
            vieren1.hide();        
            scoreVieren1.setText(String.valueOf(punten));
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_vieren1ActionPerformed

    private void vijven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vijven1ActionPerformed
        // de actie van vijven voor speler 1
        if (beurt == 1){
            punten = 0;
            if (dobbel1 == 5){
                punten = punten + 5;
            }
            if (dobbel2 == 5){
                punten = punten + 5;
            }
            if (dobbel3 == 5){
                punten = punten + 5;
            }
            if (dobbel4 == 5){
                punten = punten + 5;
            }
            if (dobbel5 == 5){
                punten = punten + 5;  
            }
            vijven1.hide();
            scoreVijven1.setText(String.valueOf(punten));
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_vijven1ActionPerformed

    private void zessen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zessen1ActionPerformed
        // de actie voor zessen van speler 1
        if (beurt == 1){
            punten = 0;    
            if (dobbel1 == 6){
                punten = punten + 6;
            }
            if (dobbel2 == 6){
                punten = punten + 6;
            }
            if (dobbel3 == 6){
                punten = punten + 6;
            }
            if (dobbel4 == 6){
                punten = punten + 6;
            }
            if (dobbel5 == 6){
                punten = punten + 6;  
            }
            zessen1.hide();
            scoreZessen1.setText(String.valueOf(punten));
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_zessen1ActionPerformed

    private void enen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enen2ActionPerformed
        // de actie voor de enen van speler 2
        if (beurt == 2){
            punten = 0;
            if (dobbel1 == 1){
                punten = punten + 1;
            }
            if (dobbel2 == 1){
                punten = punten + 1;
            }
            if (dobbel3 == 1){
                punten = punten + 1;
            }
            if (dobbel4 == 1){
                punten = punten + 1;
            }
            if (dobbel5 == 1){
                punten = punten + 1;  
            }
            enen2.hide();
            scoreEnen2.setText(String.valueOf(punten));
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_enen2ActionPerformed

    private void tweeen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweeen2ActionPerformed
        // de actie voor de tweeën van speler 2
        if (beurt == 2){
            punten = 0; 
            if (dobbel1 == 2){
                punten = punten + 2;
            }
            if (dobbel2 == 2){
                punten = punten + 2;
            }
            if (dobbel3 == 2){
                punten = punten + 2;
            }
            if (dobbel4 == 2){
                punten = punten + 2;
            }
            if (dobbel5 == 2){
                punten = punten + 2;  
            }
            tweeen2.hide(); 
            scoreTweeen2.setText(String.valueOf(punten));
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_tweeen2ActionPerformed

    private void vieren2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieren2ActionPerformed
        // de actie van vieren van speler 2
        if (beurt == 2){
            punten = 0;
            if (dobbel1 == 4){
                punten = punten + 4;
            }
            if (dobbel2 == 4){
                punten = punten + 4;
            }
            if (dobbel3 == 4){
                punten = punten + 4;
            }
            if (dobbel4 == 4){
                punten = punten + 4;
            }
            if (dobbel5 == 4){
                punten = punten + 4;  
            }
            vieren2.hide();
            scoreVieren2.setText(String.valueOf(punten));
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_vieren2ActionPerformed

    private void vijven2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vijven2ActionPerformed
        // de actie van vijven voor speler 2
        if (beurt == 2){
            punten = 0;
            if (dobbel1 == 5){
                    punten = punten + 5;
                 }
            if (dobbel2 == 5){
                    punten = punten + 5;
            }
            if (dobbel3 == 5){
                    punten = punten + 5;
            }
            if (dobbel4 == 5){
                    punten = punten + 5;
            }
            if (dobbel5 == 5){
                    punten = punten + 5;  
            }
            vijven2.hide();
            scoreVijven2.setText(String.valueOf(punten));
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_vijven2ActionPerformed

    private void zessen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zessen2ActionPerformed
        // de actie voor zessen van speler 2
        if (beurt == 2){
            punten = 0;    
           if (dobbel1 == 6){
               punten = punten + 6;
           }
           if (dobbel2 == 6){
               punten = punten + 6;
           }
           if (dobbel3 == 6){
               punten = punten + 6;
           }
           if (dobbel4 == 6){
               punten = punten + 6;
           }
           if (dobbel5 == 6){
               punten = punten + 6;  
           }
           zessen2.hide();
           scoreZessen2.setText(String.valueOf(punten));
           gooienActie();
           beurt1Actie();
           
        }
    }//GEN-LAST:event_zessen2ActionPerformed

    private void berekenKnop11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berekenKnop11ActionPerformed
        // de score van speler 1 wordt berekend
        if (enen1.isShowing() == false & tweeen1.isShowing() == false & drieen1.isShowing() == false & vieren1.isShowing() == false & vijven1.isShowing() == false & zessen1.isShowing() == false){
            puntentotaal = Integer.parseInt(scoreEnen1.getText()) + Integer.parseInt(scoreDrieen1.getText()) + Integer.parseInt(scoreTweeen1.getText()) + Integer.parseInt(scoreVieren1.getText()) + Integer.parseInt(scoreVijven1.getText()) + Integer.parseInt(scoreZessen1.getText());
            totaalBegin1.setText(String.valueOf(puntentotaal));
            if (puntentotaal >= 63){
                 puntentotaal = puntentotaal + 35;
                 bonus1.setText("35");
              }
            totaalDeel11.setText(String.valueOf(puntentotaal));
            berekenKnop11.hide();
        }
    }//GEN-LAST:event_berekenKnop11ActionPerformed

    private void berekenKnop12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berekenKnop12ActionPerformed
        //de score van speler 2 wordt berekend 
        if (enen2.isShowing() == false & tweeen2.isShowing() == false & drieen2.isShowing() == false & vieren2.isShowing() == false & vijven2.isShowing() == false & zessen2.isShowing() == false){
            puntentotaal = Integer.parseInt(scoreEnen2.getText()) + Integer.parseInt(scoreDrieen2.getText()) + Integer.parseInt(scoreTweeen2.getText()) + Integer.parseInt(scoreVieren2.getText()) + Integer.parseInt(scoreVijven2.getText()) + Integer.parseInt(scoreZessen2.getText());
            totaalBegin2.setText(String.valueOf(puntentotaal));
            if (puntentotaal >= 63){
                    puntentotaal = puntentotaal + 35;
                    bonus2.setText("35");
            }
            totaalDeel12.setText(String.valueOf(puntentotaal));
            berekenKnop12.hide();
        }

    }//GEN-LAST:event_berekenKnop12ActionPerformed

    private void threeKnop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeKnop1ActionPerformed
        // telt de score van three of a kind van speler 1 op
        if (beurt == 1){
            punten = 0;
            punten = dobbel1 + dobbel2 + dobbel3 + dobbel4 + dobbel5;
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel4){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel5){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel4){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel5){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel4 & dobbel4 == dobbel5){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel3 & dobbel3 == dobbel4){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel3 & dobbel3 == dobbel5){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel4 & dobbel4 == dobbel5){
                three1.setText(String.valueOf(punten));
            }
            if (dobbel3 == dobbel4 & dobbel4 == dobbel5){
                three1.setText(String.valueOf(punten));
            }
            threeKnop1.hide();
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_threeKnop1ActionPerformed

    private void carreKnop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreKnop1ActionPerformed
        //telt de score van carré van speler 1 op
        if (beurt == 1){
            punten = 0;
            punten = dobbel1 + dobbel2 + dobbel3 + dobbel4 + dobbel5;
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel3 == dobbel4){
                carre1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel3 == dobbel5){
                carre1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel4 & dobbel4 == dobbel5){
                carre1.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel4 & dobbel4 == dobbel5){
                carre1.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel3 & dobbel3 == dobbel4 & dobbel4 == dobbel5){
                carre1.setText(String.valueOf(punten));
            }
            carreKnop1.hide();
            gooienActie();        
            beurt2Actie();
            
        }
    }//GEN-LAST:event_carreKnop1ActionPerformed

    private void fullKnop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullKnop1ActionPerformed
        //telt de score van full house van speler 1 op
        if (beurt == 1){
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel4 == dobbel5 & dobbel1 != dobbel4){
                full1.setText("25");
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel4 & dobbel2 == dobbel5 & dobbel2 != dobbel1){
                full1.setText("25");
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel5 & dobbel2 == dobbel4 & dobbel1 != dobbel2){
                full1.setText("25");
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel4 & dobbel3 == dobbel5 & dobbel1 != dobbel3){
                full1.setText("25");
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel5 & dobbel4 == dobbel3 & dobbel1 != dobbel4){
                full1.setText("25");
            }
            if (dobbel1 == dobbel4 & dobbel4 == dobbel5 & dobbel2 == dobbel3 & dobbel1 != dobbel2){
                full1.setText("25");
            }
            if (dobbel3 == dobbel2 & dobbel2 == dobbel4 & dobbel1 == dobbel5 & dobbel1 != dobbel2){
                full1.setText("25");
            }
            if (dobbel3 == dobbel2 & dobbel2 == dobbel5 & dobbel4 == dobbel1 & dobbel1 != dobbel2){
                full1.setText("25");
            }
            if (dobbel4 == dobbel2 & dobbel2 == dobbel5 & dobbel1 == dobbel3 & dobbel1 != dobbel2){
                full1.setText("25");
            }
            if (dobbel3 == dobbel4 & dobbel5 == dobbel3 & dobbel1 == dobbel2 & dobbel1 != dobbel4){
                full1.setText("25");
            }      
            fullKnop1.hide();  
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_fullKnop1ActionPerformed

    private void kleineKnop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kleineKnop1ActionPerformed
        // telt de score van kleine straat van speler 1 op
        if (beurt == 1){
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 == 24){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel5 == 24){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel5 * dobbel4 == 24){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel5 * dobbel3 * dobbel4 == 24){
            kleine1.setText("30");
            }
            if (dobbel5 * dobbel2 * dobbel3 * dobbel4 == 24){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 == 120){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel5 == 120){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel5 * dobbel4 == 120){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel5 * dobbel3 * dobbel4 == 120){
                kleine1.setText("30");
            }
            if (dobbel5 * dobbel2 * dobbel3 * dobbel4 == 120){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 == 360){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel5 == 360){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel5 * dobbel4 == 360){
                kleine1.setText("30");
            }
            if (dobbel1 * dobbel5 * dobbel3 * dobbel4 == 360){
                kleine1.setText("30");
            }
            if (dobbel5 * dobbel2 * dobbel3 * dobbel4 == 360){
                kleine1.setText("30");
            }
            kleineKnop1.hide();
            gooienActie();       
            beurt2Actie();
            
        }
    }//GEN-LAST:event_kleineKnop1ActionPerformed

    private void groteKnop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groteKnop1ActionPerformed
        // telt de score van grote straat van speler 1 op
        if (beurt == 1){
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 * dobbel5 == 120){
                grote1.setText("40");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 * dobbel5 == 720){
                grote1.setText("40");
            }
            groteKnop1.hide();
            gooienActie();
            beurt2Actie();
            resetDobbel();
        }
    }//GEN-LAST:event_groteKnop1ActionPerformed

    private void topscoreKnop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topscoreKnop1ActionPerformed
        //telt de score van topscore van speler 1 op
        if (beurt == 1){
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel3 == dobbel4 & dobbel4 == dobbel5){
                topscore1.setText("50");
                    }
            topscoreKnop1.hide();
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_topscoreKnop1ActionPerformed

    private void chanceKnop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chanceKnop1ActionPerformed
        // telt de score van chance van speler 1 op
        if (beurt == 1){
            punten = 0;
            punten = dobbel1 + dobbel2 + dobbel3 + dobbel4 + dobbel5;
            chance1.setText(String.valueOf(punten));
            chanceKnop1.hide();
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_chanceKnop1ActionPerformed

    private void chanceKnop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chanceKnop2ActionPerformed
        // telt de score van chance van speler 1 op
        if (beurt == 1){
            punten = 0;
            punten = dobbel1 + dobbel2 + dobbel3 + dobbel4 + dobbel5;
            chance2.setText(String.valueOf(punten));
            chanceKnop2.hide();
            gooienActie();
            beurt2Actie();
            
        }
    }//GEN-LAST:event_chanceKnop2ActionPerformed

    private void topscoreKnop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topscoreKnop2ActionPerformed
        //telt de score van topscore van speler 2 op
        if (beurt == 2){
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel3 == dobbel4 & dobbel4 == dobbel5){
                topscore2.setText("50");
                    }
            topscoreKnop2.hide();
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_topscoreKnop2ActionPerformed

    private void groteKnop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groteKnop2ActionPerformed
        // telt de score van grote straat van speler 2 op
        if (beurt == 2){
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 * dobbel5 == 120){
                grote1.setText("40");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 * dobbel5 == 720){
                grote1.setText("40");
            }
            groteKnop1.hide();
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_groteKnop2ActionPerformed

    private void kleineKnop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kleineKnop2ActionPerformed
        // telt de score van kleine straat van speler 2 op
        if (beurt == 2){
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 == 24){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel5 == 24){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel5 * dobbel4 == 24){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel5 * dobbel3 * dobbel4 == 24){
                kleine2.setText("30");
            }
            if (dobbel5 * dobbel2 * dobbel3 * dobbel4 == 24){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 == 120){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel5 == 120){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel5 * dobbel4 == 120){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel5 * dobbel3 * dobbel4 == 120){
                kleine2.setText("30");
            }
            if (dobbel5 * dobbel2 * dobbel3 * dobbel4 == 120){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel4 == 360){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel3 * dobbel5 == 360){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel2 * dobbel5 * dobbel4 == 360){
                kleine2.setText("30");
            }
            if (dobbel1 * dobbel5 * dobbel3 * dobbel4 == 360){
                kleine2.setText("30");
            }
            if (dobbel5 * dobbel2 * dobbel3 * dobbel4 == 360){
                kleine2.setText("30");
            }
        
            kleineKnop2.hide();
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_kleineKnop2ActionPerformed

    private void carreKnop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreKnop2ActionPerformed
        //telt de score van carré van speler 2 op
        if (beurt == 2){
            punten = 0;
            punten = dobbel1 + dobbel2 + dobbel3 + dobbel4 + dobbel5;
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel3 == dobbel4){
                carre2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel3 == dobbel5){
                carre2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel4 & dobbel4 == dobbel5){
                carre2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel4 & dobbel4 == dobbel5){
                carre2.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel3 & dobbel3 == dobbel4 & dobbel4 == dobbel5){
                carre2.setText(String.valueOf(punten));
            }
        
            carreKnop2.hide();
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_carreKnop2ActionPerformed

    private void fullKnop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullKnop2ActionPerformed
        //telt de score van full house van speler 2 op
        if (beurt == 2){
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3 & dobbel4 == dobbel5 & dobbel1 != dobbel4){
                full2.setText("25");
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel4 & dobbel2 == dobbel5 & dobbel2 != dobbel1){
                full2.setText("25");
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel5 & dobbel2 == dobbel4 & dobbel1 != dobbel2){
                full2.setText("25");
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel4 & dobbel3 == dobbel5 & dobbel1 != dobbel3){
                full2.setText("25");
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel5 & dobbel4 == dobbel3 & dobbel1 != dobbel4){
                full2.setText("25");
            }
            if (dobbel1 == dobbel4 & dobbel4 == dobbel5 & dobbel2 == dobbel3 & dobbel1 != dobbel2){
                full2.setText("25");
            }
            if (dobbel3 == dobbel2 & dobbel2 == dobbel4 & dobbel1 == dobbel5 & dobbel1 != dobbel2){
                full2.setText("25");
            }
            if (dobbel3 == dobbel2 & dobbel2 == dobbel5 & dobbel4 == dobbel1 & dobbel1 != dobbel2){
                full2.setText("25");
            }
            if (dobbel4 == dobbel2 & dobbel2 == dobbel5 & dobbel1 == dobbel3 & dobbel1 != dobbel2){
                full2.setText("25");
            }
            if (dobbel3 == dobbel4 & dobbel5 == dobbel3 & dobbel1 == dobbel2 & dobbel1 != dobbel4){
                full2.setText("25");
            }      
            fullKnop2.hide();
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_fullKnop2ActionPerformed

    private void threeKnop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeKnop2ActionPerformed
        // telt de score van three of a kind van speler 2 op
        if (beurt == 2){
            punten = 0;
            punten = dobbel1 + dobbel2 + dobbel3 + dobbel4 + dobbel5;
            if (dobbel1 == dobbel2 & dobbel2 == dobbel3){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel4){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel2 & dobbel2 == dobbel5){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel4){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel3 & dobbel3 == dobbel5){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel1 == dobbel4 & dobbel4 == dobbel5){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel3 & dobbel3 == dobbel4){
               three2.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel3 & dobbel3 == dobbel5){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel2 == dobbel4 & dobbel4 == dobbel5){
                three2.setText(String.valueOf(punten));
            }
            if (dobbel3 == dobbel4 & dobbel4 == dobbel5){
                three2.setText(String.valueOf(punten));
            }
            threeKnop2.hide();
            gooienActie();
            beurt1Actie();
            
        }
    }//GEN-LAST:event_threeKnop2ActionPerformed

    private void berekenKnop21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berekenKnop21ActionPerformed
        // Berekend de totale score van deel 2 van speler 1
        if (three1.isVisible() == false & carre1.isVisible() == false & full1.isVisible() == false & kleine1.isVisible() == false & grote1.isVisible() == false & topscore1.isVisible() == false & chance1.isVisible() == false){
            puntentotaal = Integer.parseInt(three1.getText()) + Integer.parseInt(carre1.getText()) + Integer.parseInt(full1.getText()) + Integer.parseInt(kleine1.getText()) + Integer.parseInt(grote1.getText()) + Integer.parseInt(topscore1.getText()) + Integer.parseInt(chance1.getText());
            totaalDeel21.setText(String.valueOf(puntentotaal));
            berekenKnop21.hide();
        }
    }//GEN-LAST:event_berekenKnop21ActionPerformed

    private void berekenKnop22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berekenKnop22ActionPerformed
        // Berekend de totale score van deel 2 van speler 2
        if (three2.isVisible() == false & carre2.isVisible() == false & full2.isVisible() == false & kleine2.isVisible() == false & grote2.isVisible() == false & topscore2.isVisible() == false & chance2.isVisible() == false){
            puntentotaal = Integer.parseInt(three2.getText()) + Integer.parseInt(carre2.getText()) + Integer.parseInt(full2.getText()) + Integer.parseInt(kleine2.getText()) + Integer.parseInt(grote2.getText()) + Integer.parseInt(topscore2.getText()) + Integer.parseInt(chance2.getText());
            totaalDeel22.setText(String.valueOf(puntentotaal));
            berekenKnop22.hide();
        }
    }//GEN-LAST:event_berekenKnop22ActionPerformed

    private void berekenKnopEindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berekenKnopEindActionPerformed
        // berekend de totale score van alles en wie de winnaar is
        if (berekenKnop11.isVisible() == false & berekenKnop12.isVisible() == false & berekenKnop21.isVisible() == false & berekenKnop22.isVisible() == false){
            score1 = Integer.parseInt(totaalDeel11.getText()) + Integer.parseInt(totaalDeel12.getText());
            score2 = Integer.parseInt(totaalDeel21.getText()) + Integer.parseInt(totaalDeel22.getText());
            totaalScore1.setText(String.valueOf(score1));
            totaalScore2.setText(String.valueOf(score2));
            if (score1 > score2){
                winnaar.setText("Winnaar: Speler 1!");           
            }else if (score1 == score2){
                winnaar.setText("Gelijk spel!");
            }else if (score1 < score2){
                winnaar.setText("Winnaar: Speler 2!");
            }
        }
        
    }//GEN-LAST:event_berekenKnopEindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yahtzee1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aantalGooien;
    private javax.swing.JLabel asdf;
    private javax.swing.JButton berekenKnop11;
    private javax.swing.JButton berekenKnop12;
    private javax.swing.JButton berekenKnop21;
    private javax.swing.JButton berekenKnop22;
    private javax.swing.JButton berekenKnopEind;
    private javax.swing.JLabel beurtTekst;
    private javax.swing.JLabel bonus1;
    private javax.swing.JLabel bonus2;
    private javax.swing.JLabel carre1;
    private javax.swing.JLabel carre2;
    private javax.swing.JButton carreKnop1;
    private javax.swing.JButton carreKnop2;
    private javax.swing.JLabel chance1;
    private javax.swing.JLabel chance2;
    private javax.swing.JButton chanceKnop1;
    private javax.swing.JButton chanceKnop2;
    private javax.swing.JLabel dads;
    private javax.swing.JButton dobbelKnopAlle;
    private javax.swing.JLabel dobbelVak1;
    private javax.swing.JLabel dobbelVak2;
    private javax.swing.JLabel dobbelVak3;
    private javax.swing.JLabel dobbelVak4;
    private javax.swing.JLabel dobbelVak5;
    private javax.swing.JCheckBox dobbelsteen1;
    private javax.swing.JCheckBox dobbelsteen2;
    private javax.swing.JCheckBox dobbelsteen3;
    private javax.swing.JCheckBox dobbelsteen4;
    private javax.swing.JCheckBox dobbelsteen5;
    private javax.swing.JButton drieen1;
    private javax.swing.JButton drieen2;
    private javax.swing.JButton enen1;
    private javax.swing.JButton enen2;
    private javax.swing.JLabel fdsa;
    private javax.swing.JLabel full1;
    private javax.swing.JLabel full2;
    private javax.swing.JButton fullKnop1;
    private javax.swing.JButton fullKnop2;
    private javax.swing.JLabel grote1;
    private javax.swing.JLabel grote2;
    private javax.swing.JButton groteKnop1;
    private javax.swing.JButton groteKnop2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel kleine1;
    private javax.swing.JLabel kleine2;
    private javax.swing.JButton kleineKnop1;
    private javax.swing.JButton kleineKnop2;
    private javax.swing.JLabel sadfsd;
    private javax.swing.JLabel scoreDrieen1;
    private javax.swing.JLabel scoreDrieen2;
    private javax.swing.JLabel scoreEnen1;
    private javax.swing.JLabel scoreEnen2;
    private javax.swing.JLabel scoreTweeen1;
    private javax.swing.JLabel scoreTweeen2;
    private javax.swing.JLabel scoreVieren1;
    private javax.swing.JLabel scoreVieren2;
    private javax.swing.JLabel scoreVijven1;
    private javax.swing.JLabel scoreVijven2;
    private javax.swing.JLabel scoreZessen1;
    private javax.swing.JLabel scoreZessen2;
    private javax.swing.JLabel three1;
    private javax.swing.JLabel three2;
    private javax.swing.JButton threeKnop1;
    private javax.swing.JButton threeKnop2;
    private javax.swing.JLabel topscore1;
    private javax.swing.JLabel topscore2;
    private javax.swing.JButton topscoreKnop1;
    private javax.swing.JButton topscoreKnop2;
    private javax.swing.JLabel totaalBegin1;
    private javax.swing.JLabel totaalBegin2;
    private javax.swing.JLabel totaalDeel11;
    private javax.swing.JLabel totaalDeel12;
    private javax.swing.JLabel totaalDeel21;
    private javax.swing.JLabel totaalDeel22;
    private javax.swing.JLabel totaalScore1;
    private javax.swing.JLabel totaalScore2;
    private javax.swing.JButton tweeen1;
    private javax.swing.JButton tweeen2;
    private javax.swing.JLabel vasas;
    private javax.swing.JButton vieren1;
    private javax.swing.JButton vieren2;
    private javax.swing.JButton vijven1;
    private javax.swing.JButton vijven2;
    private javax.swing.JLabel winnaar;
    private javax.swing.JLabel zcxv;
    private javax.swing.JButton zessen1;
    private javax.swing.JButton zessen2;
    // End of variables declaration//GEN-END:variables
}
